// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SC1015",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "SC1015",
            targets: ["AppModule"],
            bundleIdentifier: "com.limdingwen.SC1015",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/lucaszischka/BottomSheet", "2.0.0"..<"3.0.0"),
        .package(url: "https://github.com/AppPear/ChartView", "1.0.0"..<"2.0.0"),
        .package(url: "https://github.com/AppPear/ChartView", .exact("2.0.0-beta"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "BottomSheet", package: "bottomsheet"),
                .product(name: "SwiftUICharts", package: "chartview")
            ],
            path: "."
        )
    ]
)